twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # Add global variables here
        site_name: 'SahaCare'
    paths:
        '%kernel.project_dir%/public/images': images
